language: node_js
node_js:
  - '0.10'
  - '0.12'
env:
  global:
    - secure: AXIfhVjEMvK6yM3GVzFDoIdtldfzJSMNZ1ITbTxCysp4b/mUhdQODWPfvK4YRNQZxqoVHmua0xyhPULq4Uw/htm94PMY71PTYWaCs74der0nAfm+ofA5JLorGVMPZ5ls70R5F2uIiJhXNr5gt2KFT+ISVl7P3uSg26MhkAwJnTqrAeekTEKzIYWOe+yK5X0w2bNagRgh+fNWI9RAX9tCBOiOg+xNMiWJ1JJmTQ2UVqHfyGKgO7g79I8t1O83yAv9RwGhyTzoGa5aIf8E3kKxlkpkmULIfsmIhvnj1jpU8gtmnQHWqudKovELA92qV5eKJ91TZmoJZoqpFqFl9jFTYZMeKqWihb6wIrUtWwfWb03vbviZ+UsbVEE2kYyt3P71Tryop9UbRGbjDEu0fAQiGd364zIGIF+q7y0FfW+1kXJlWZFIdaC5p9UXG2+chSwtOdYvcZ7Uz5vGlY2DvdpU/Z4ysXgC+1to7swMDDvNXvu2BYw8Yzv4cXfgikr5PPt/bqau8CJXoxB0oBkIAJR6Dh0Ex5Y9BFBuSpbcGjVM3/T/APL5sdv1L+ceZtCqMoQBU6O5Ra1Lx3jRc3v6Gxm5ByUeUA3HZpyxk8ofOVU+5tKNkSerVLEeJaejgkAfF14VT8G9Dh6RCTuaBzSgJh8NIECEzrMwRVksN2EACs2cBPo=
